Repository swagger-api/apidom, pull requests merged in 2024-07, with the labels that each got.

#4230 fix(ns-openapi-3-1): set example to first element of examples in parameter examples refractor plugin
  packages/apidom-ns-openapi-3-1/src/refractor/plugins/normalize-parameter-examples.ts
  packages/apidom-ns-openapi-3-1/test/refractor/plugins/normalize-parameter-examples/paths/__snapshots__/index.ts.snap
Labels: bug, OpenAPI 3.1, ApiDOM

#4271 docs(README): specify version of node-gyp prerequisites
  README.md
Labels: documentation, enhancement, ApiDOM

#4278 ci: release packages to GitHub Package Registry
  .github/workflows/release-to-GPR.yml
Labels: enhancement
