Repository swagger-api/apidom, pull requests merged in 2025-05, with the labels that each got.

#4904 fix(reference): use spec compliant JSON Pointer implementation
  packages/apidom-reference/src/dereference/strategies/apidom/visitor.ts
  packages/apidom-reference/src/dereference/strategies/asyncapi-2/visitor.ts
  packages/apidom-reference/src/dereference/strategies/openapi-2/visitor.ts
  packages/apidom-reference/src/dereference/strategies/openapi-3-0/visitor.ts
  packages/apidom-reference/src/dereference/strategies/openapi-3-1/selectors/uri.ts
  packages/apidom-reference/src/dereference/strategies/openapi-3-1/visitor.ts
  packages/apidom-reference/test/dereference/strategies/asyncapi-2/channel-item-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/asyncapi-2/reference-object/index.ts
  packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-2/json-reference-object/index.ts
  packages/apidom-reference/test/dereference/strategies/openapi-2/path-item-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-2/reference-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-2/reference-object/index.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-0/example-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-0/link-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-0/link-object/index.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-0/path-item-object/index.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-0/reference-object/index.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-1/example-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-1/link-object/index.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-1/path-item-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-1/reference-object/index.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/dereference-apidom.ts
  packages/apidom-reference/test/dereference/strategies/openapi-3-1/schema-object/index.ts
  packages/apidom-reference/test/tsconfig.json
Labels: enhancement

#4926 fix(security): update Axios to non-vulnerable 1.9.0 version
  package-lock.json
  packages/apidom-reference/package.json
Labels: dependencies

#4940 fix(core): fix custom deep merge not affecting nested properties
  packages/apidom-core/src/merge/deepmerge.ts
  packages/apidom-core/test/merge/deepmerge.ts
Labels: bug
